version: "3"
services:
  redis-server:
    image: redis:latest
    restart: on-failure
  flaskapp:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    image: flaskapp:latest
    ports: 
      - 1234:80
    depends_on: 
      - redis-server
    restart: on-failure